// This file is auto-generated by scripts/update_blog.js.
// Do not edit this file directly.
import article_2025_05_08_hello_world from './articles/2025-05-08-hello-world.json';

const articles = [
  { markdown: article_2025_05_08_hello_world, stem: '2025-05-08-hello-world' },
];

export default articles;
