// This file is auto-generated by scripts/update_blog.js.
// Do not edit this file directly.
import article_2025_05_27_hello_world from './articles/2025-05-27-hello-world.json';

const articles = [article_2025_05_27_hello_world];

export default articles;
