// This file is auto-generated by scripts/update_blog.js.
// Do not edit this file directly.
import article_2025_05_08_hello_world from './articles/2025-05-08-hello-world.json';
import article_2025_06_16_rust_iterators from './articles/2025-06-16-rust-iterators.json';

const articles = [
  { markdown: article_2025_05_08_hello_world, stem: '2025-05-08-hello-world' },
  {
    markdown: article_2025_06_16_rust_iterators,
    stem: '2025-06-16-rust-iterators',
  },
];

export default articles;
