'use strict';

import fs from 'fs';
import matter from 'gray-matter';

let articles = [];
let imports = [];

for (const fileName of fs.readdirSync('blog')) {
  const [stem, ext] = fileName.split('.');
  if (ext === 'md') {
    const file = matter(fs.readFileSync(`blog/${fileName}`, 'utf8'));
    fs.writeFileSync(
      `src/pages/Blog/articles/${stem}.json`,
      JSON.stringify(file)
    );
    const article = `article_${stem.replace(/[- ]/g, '_')}`;
    articles.push(article);
    imports.push(`import ${article} from './articles/${stem}.json';`);
  }
}

const articles_js = `
// This file is auto-generated by scripts/update_blog.js.
// Do not edit this file directly.
${imports.join('\n')}

const articles = [
  ${articles.join(',\n  ')},
];

export default articles;
`;
fs.writeFileSync(`src/pages/Blog/articles.jsx`, articles_js);
